services:
  - type: web
    name: disease-prediction
    env: python
    plan: free
    rootDir: healthcare
    buildCommand: "./build.sh"
    startCommand: "gunicorn healthcare.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
